import express from 'express';
const router = express.Router();

import authRoutes from './auth.routes.js';
import uploadRoutes from './upload.routes.js';
import adminRoutes from './admin.routes.js';
import siteRoutes from './site.routes.js';
import farmerRoutes from './farmer.routes.js';
import commissionRoutes from './commission.routes.js';
import plotCommissionV2Routes from './plotCommissionV2.routes.js';
import cashflowRoutes from './cashflow.routes.js';
import firmRoutes from './firm.routes.js';
import plotRoutes from './plot.routes.js';
import plotDocumentRoutes from './plotDocument.routes.js';
import dmsDocumentRoutes from './dmsDocument.routes.js';
import forecastRoutes from './forecast.routes.js';
import expenseRoutes from './expense.routes.js';
import registryRoutes from './registry.routes.js';
import memberRoutes from './member.routes.js';
import daybookRoutes from './daybook.routes.js';
import imprestRoutes from './imprest.routes.js';
import documentImprestRoutes from './documentImprest.routes.js';
import editRequestRoutes from './editRequest.routes.js';
import permissionRoutes from './permission.routes.js';
import memberCategoryRoutes from './memberCategory.routes.js';
import expenseCategoryRoutes from './expenseCategory.routes.js';
import activityRoutes from './activity.routes.js';
import excelRoutes from './excel.routes.js';
import folderRoutes from './folder.routes.js';
import approvalRoutes from './approval.routes.js';
import chatRoutes from './chat.routes.js';
import vendorRoutes from './vendor.routes.js';
import dashboardPermissionRoutes from './dashboardPermission.routes.js';
import upiRoutes from './upi.routes.js';
import signatureRoutes from './signature.routes.js';

router.use('/auth', authRoutes);
router.use('/upload', uploadRoutes);
router.use('/admin', adminRoutes);
router.use('/sites', siteRoutes);
router.use('/farmers', farmerRoutes);
router.use('/commissions', commissionRoutes);
router.use('/plot-commission', plotCommissionV2Routes);
router.use('/cashflow', cashflowRoutes);
router.use('/firms', firmRoutes);
router.use('/plots', plotRoutes);
router.use('/plot-documents', plotDocumentRoutes);
router.use('/documents', dmsDocumentRoutes);
router.use('/forecast', forecastRoutes);
router.use('/expenses', expenseRoutes);
router.use('/registries', registryRoutes);
router.use('/members', memberRoutes);
router.use('/daybook', daybookRoutes);
router.use('/imprest', imprestRoutes);
router.use('/document-imprest', documentImprestRoutes);
router.use('/edit-requests', editRequestRoutes);
router.use('/permissions', permissionRoutes);
router.use('/member-categories', memberCategoryRoutes);
router.use('/expense-categories', expenseCategoryRoutes);
router.use('/activity', activityRoutes);
router.use('/excel', excelRoutes);
router.use('/folders', folderRoutes);
router.use('/approvals', approvalRoutes);
router.use('/chat', chatRoutes);
router.use('/vendors', vendorRoutes);
router.use('/dashboard-permissions', dashboardPermissionRoutes);
router.use('/upi', upiRoutes);
router.use('/signatures', signatureRoutes);
export default router;