// Local API for frontend development. Schedulers run only in src/server.js.
import http from 'node:http';
import app from '../src/app.js';
import { initSocket } from '../src/config/socket.js';
import { initCache } from '../src/config/cache.js';
import { backupMaintenanceEnabled } from '../src/middlewares/backupMaintenance.middleware.js';
import pool from '../src/config/db.js';
import { up as migrateMemberSiteSharing } from '../src/migrations/187_member_site_sharing.js';
import { up as migrateMemberIdentityLinking } from '../src/migrations/192_member_identity_linking.js';
import { up as migrateMemberIdentityConsolidation } from '../src/migrations/194_member_identity_consolidation.js';
import { up as migrateTdsDeducteeMapping } from '../src/migrations/191_tds_deductee_mapping.js';
import { up as migrateDataStorage } from '../src/migrations/193_data_storage.js';
import { up as migrateTdsFinancialSettlements } from '../src/migrations/198_tds_financial_settlements.js';
import { up as migrateImprestApprovalIndexes } from '../src/migrations/197_imprest_approval_activity_indexes.js';
import { up as migrateImprestCashGuard } from '../src/migrations/195_imprest_cash_funding_guard.js';
import { up as migrateExistingVoucherGaps } from '../src/migrations/196_existing_voucher_gaps_filled.js';
await migrateMemberSiteSharing(pool);
await migrateMemberIdentityLinking(pool);
await migrateMemberIdentityConsolidation(pool);
await migrateTdsDeducteeMapping(pool);
await migrateTdsFinancialSettlements(pool);
await migrateDataStorage(pool);
await migrateImprestCashGuard(pool);
await migrateImprestApprovalIndexes(pool);
await migrateExistingVoucherGaps(pool);
const server = http.createServer(app);
if (!backupMaintenanceEnabled()) initSocket(server);
initCache();
const port = Number(process.env.LOCAL_API_PORT || 3000);
server.listen(port, '127.0.0.1', () => console.log(`Local development API ready on http://127.0.0.1:${port}`));
for (const signal of ['SIGTERM','SIGINT']) process.once(signal, () => server.close(() => process.exit(0)));
